import { LuminanceProps } from "../lib/Luminance";

export const LUMINANCE_DEFAULTS: LuminanceProps = {
  disabled: false,
  spring: true,
  springStiffness: 0.15,
  springDamping: 0.25,
  reflectionEnabled: true,
  reflectionType: "linear",
  reflectionAngle: 90,
  reflectionPositionX: 50,
  reflectionPositionY: 50,
  reflectionColorStart: "#fff",
  reflectionColorEnd: "#fff0",
  reflectionStep1: 0,
  reflectionStep2: 50,
  reflectionIntensity: 0.8,
  reflectionBlur: 30,
  reflectionSize: 1.5,
  glowEnabled: false,
  glowType: "external",
  glowColor: "#fff",
  glowBlur: 20,
  glowIntensity: 0.8,
  glowSpread: 5,
  borderEnabled: false,
  borderVariant: "activate",
  borderColor: "#fff",
  borderWidth: 2,
  borderIntensity: 1,
  children: null,
};
